using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using NftFaucetRadzen.Components;
using NftFaucetRadzen.Models;
using Radzen;

namespace NftFaucetRadzen.Pages;

public partial class ProviderPage : BasicComponent
{
    [Inject]
    protected IJSRuntime JSRuntime { get; set; }

    [Inject]
    protected DialogService DialogService { get; set; }

    [Inject]
    protected TooltipService TooltipService { get; set; }

    [Inject]
    protected ContextMenuService ContextMenuService { get; set; }

    [Inject]
    protected NotificationService NotificationService { get; set; }

    protected CardListItem[] Providers { get; private set; } = new CardListItem[]
    {
        new CardListItem
        {
            Id = Guid.Parse("ded55b2b-8139-4251-a0fc-ba620f9727c9"),
            ImageName = "ecdsa.svg",
            Header = "Autogenerated keys",
            IsDisabled = false,
            Properties = new[]
            {
                new CardListItemProperty { Name = "Installed", Value = "yes" },
                new CardListItemProperty { Name = "Connected", Value = "no" },
            },
            Badges = Array.Empty<CardListItemBadge>(),
        },
        new CardListItem
        {
            Id = Guid.Parse("3367b9bb-f50c-4768-aeb3-9ac14d4c3987"),
            ImageName = "metamask_fox.svg",
            Header = "Metamask",
            IsDisabled = false,
            Properties = new[]
            {
                new CardListItemProperty { Name = "Installed", Value = "yes" },
                new CardListItemProperty { Name = "Connected", Value = "no" },
            },
            Badges = new[]
            {
                new CardListItemBadge { Style = BadgeStyle.Success, Text = "Recommended" },
            },
        }
    };
}
